package org.geometerplus.android.fbreader.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class BooksDaoSession extends AbstractDaoSession {

  private final DaoConfig mBookmarksDaoConfig;

  private final BookmarksDao mBookmarksDao;

  public BooksDaoSession(SQLiteDatabase db, IdentityScopeType type,
      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
    super(db);

    mBookmarksDaoConfig = daoConfigMap.get(BookmarksDao.class).clone();
    mBookmarksDaoConfig.initIdentityScope(type);

    mBookmarksDao = new BookmarksDao(mBookmarksDaoConfig, this);

    registerDao(Bookmark.class, mBookmarksDao);
  }

  public void clear() {
    mBookmarksDaoConfig.getIdentityScope().clear();
  }

  public BookmarksDao getBookmarksDao() {
    return mBookmarksDao;
  }
}
